-- Create databases for each cluster
CREATE DATABASE k3s_cluster1;
CREATE DATABASE k3s_cluster2;

-- Create dedicated user for K3s
CREATE USER k3s WITH PASSWORD '${random_password.k3s_password.result}';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE k3s_cluster1 TO k3s;
GRANT ALL PRIVILEGES ON DATABASE k3s_cluster2 TO k3s;

-- Connect to each database and grant schema permissions
\c k3s_cluster1;
GRANT ALL ON SCHEMA public TO k3s;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO k3s;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO k3s;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO k3s;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO k3s;

\c k3s_cluster2;
GRANT ALL ON SCHEMA public TO k3s;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO k3s;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO k3s;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO k3s;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO k3s;
